const SELECTED: any[] = [
  {
    "id": "gelato-toys-1",
    "sku": "GEL-KIDS-POSTER-ABC",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "ABC Adventure Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-2",
    "sku": "GEL-KIDS-POSTER-SPACE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Solar System Kids Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-3",
    "sku": "GEL-KIDS-POSTER-ANIMALS",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Animals Wall Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 20.9,
    "image": "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-4",
    "sku": "GEL-KIDS-POSTER-COUNT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Counting Forest Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-5",
    "sku": "GEL-KIDS-TEE-EXPLORE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Little Explorer Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 24.9,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-6",
    "sku": "GEL-KIDS-TEE-PLAY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Play Mode On T-Shirt",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1503919545889-aef636e10ad0?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-7",
    "sku": "GEL-KIDS-TEE-STORY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Storytime Hero Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-8",
    "sku": "GEL-KIDS-TEE-RAINBOW",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Rainbow Crew Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-9",
    "sku": "GEL-KIDS-POSTER-BUILD",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Build & Learn Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1587654780291-39c9404d745b?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-10",
    "sku": "GEL-KIDS-POSTER-DINO",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Dinosaurs Dino Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 21.5,
    "image": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-11",
    "sku": "GEL-KIDS-TEE-MAKER",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Future Maker Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-12",
    "sku": "GEL-KIDS-POSTER-DREAM",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Bedtime Dreams Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-13",
    "sku": "GEL-KIDS-POSTER-OCEAN",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ocean Friends Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 20.5,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-14",
    "sku": "GEL-KIDS-TEE-SCIENCE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Little Scientist Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 24.5,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-15",
    "sku": "GEL-KIDS-POSTER-SHAPES",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Shapes & Colors Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1587654780291-39c9404d745b?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-16",
    "sku": "GEL-KIDS-POSTER-ROCKET",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Rocket Launch Kids Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 21.5,
    "image": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-17",
    "sku": "GEL-KIDS-TEE-CHEF",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Little Chef Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 23.5,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-18",
    "sku": "GEL-KIDS-POSTER-ZOO",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Alphabet Zoo Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 20.5,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-19",
    "sku": "GEL-KIDS-TEE-PLAYGROUND",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Playground Hero Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 22.5,
    "image": "https://images.unsplash.com/photo-1503919545889-aef636e10ad0?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-20",
    "sku": "GEL-KIDS-POSTER-FAIRY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Fairy Tale Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-21",
    "sku": "GEL-KIDS-TEE-INVENTOR",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Junior Inventor Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 24.5,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-22",
    "sku": "GEL-KIDS-POSTER-WEATHER",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Weather Watch Kids Poster",
    "category": "Educational",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-23",
    "sku": "GEL-KIDS-TEE-KIND",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Super Kind Soft Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-24",
    "sku": "GEL-KIDS-POSTER-VIKING",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Viking Adventure Poster",
    "category": "Kids Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "toys"
  },
  {
    "id": "gelato-toys-25",
    "sku": "GEL-KIDS-TEE-TRAVELER",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tiny Traveler Kids Tee",
    "category": "Kids Apparel",
    "supplierPriceUsd": 8.2,
    "suggestedRetailUsd": 25.5,
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "toys"
  }
];
const SECTOR_ALIASES: Record<string, string> = {
  "beauty": "beauty",
  "perfume": "beauty",
  "perfumes": "beauty",
  "skincare": "beauty",
  "toys": "toys",
  "kids": "toys",
  "kid": "toys",
  "children": "toys",
  "electronics": "electronics",
  "tech": "electronics",
  "technology": "electronics",
  "pet supplies": "pet supplies",
  "pets": "pet supplies",
  "pet": "pet supplies",
  "home living": "home living",
  "home": "home living",
  "living": "home living",
  "fitness": "fitness",
  "outdoor": "fitness",
  "sports": "fitness",
  "solar energy": "solar energy",
  "energy": "solar energy",
  "solar": "solar energy",
  "car accessories": "car accessories",
  "car": "car accessories",
  "auto": "car accessories",
  "automotive": "car accessories"
};
function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}
function resolveSector(raw: string) {
  const key = String(raw || "").toLowerCase().trim();
  if (!key) return SELECTED[0]?.sector || "beauty";
  if (SECTOR_ALIASES[key]) return SECTOR_ALIASES[key];
  for (const [alias, sector] of Object.entries(SECTOR_ALIASES)) {
    if (key.includes(alias) || alias.includes(key)) return sector;
  }
  return key;
}
function curated(sector: string) {
  return SELECTED
    .filter((p) => !p.sector || String(p.sector).toLowerCase() === sector)
    .map((p, i) => ({
      id: String(p.id || `gelato-selected-${i}`),
      sku: String(p.sku || ""),
      supplier: "Gelato",
      provider: "gelato",
      name: String(p.name || "Gelato product"),
      category: String(p.category || sector),
      supplierPriceUsd: money(p.supplierPriceUsd) || money(p.suggestedRetailUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd) || money(p.supplierPriceUsd),
      image: String(p.image || ""),
      sector: String(p.sector || sector),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}
export default async (req: Request, context: any) => {
  if (req.method !== "GET") return Response.json({ error: "Method not allowed" }, { status: 405 });
  const url = new URL(req.url);
  const wanted = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const defaultSector = String(SELECTED[0]?.sector || "beauty");
  const sector = resolveSector(wanted || defaultSector);
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  const products = curated(sector).slice(0, 30);
  return Response.json(
    { ok: true, supplier: "gelato", sector, query: sector, products, count: products.length, source: "gelato-selected-primary", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers }
  );
};
export const config = { path: "/api/gelato-products" };
